Repository jentic/arazzo-engine, pull requests merged in 2025-08, with the labels that each got.

#22 Feat: Server URL Resolution via var-name
  runner/arazzo_runner/executor/server_processor.py
  runner/pyproject.toml
  runner/tests/executor/test_server_processor.py
Labels: enhancement

#23 test(executor): compare URLs safely
  runner/tests/executor/test_execute_operation_with_server_vars.py
Labels: enhancement

#31 style(lint): amend runner code to be lint compliant
  runner/arazzo_runner/__init__.py
  runner/arazzo_runner/__main__.py
  runner/arazzo_runner/auth/auth_parser.py
  runner/arazzo_runner/auth/auth_processor.py
  runner/arazzo_runner/auth/credentials/fetch.py
  runner/arazzo_runner/auth/credentials/models.py
  runner/arazzo_runner/auth/credentials/provider.py
  runner/arazzo_runner/auth/credentials/transform.py
  runner/arazzo_runner/auth/credentials/validate.py
  runner/arazzo_runner/auth/models.py
  runner/arazzo_runner/blob_store.py
  runner/arazzo_runner/blob_utils.py
  runner/arazzo_runner/evaluator.py
  runner/arazzo_runner/executor/operation_finder.py
  runner/arazzo_runner/executor/output_extractor.py
  runner/arazzo_runner/executor/parameter_processor.py
  runner/arazzo_runner/executor/server_processor.py
  runner/arazzo_runner/executor/step_executor.py
  runner/arazzo_runner/executor/success_criteria.py
  runner/arazzo_runner/extractor/openapi_extractor.py
  runner/arazzo_runner/http.py
  runner/arazzo_runner/models.py
  runner/arazzo_runner/runner.py
  runner/arazzo_runner/utils.py
  runner/pyproject.toml
  runner/tests/auth/credentials/test_fetch.py
  runner/tests/auth/credentials/test_provider.py
  runner/tests/auth/credentials/test_security_scheme.py
  runner/tests/auth/test_auth_parser.py
  runner/tests/auth/test_auth_processor.py
  runner/tests/base_test.py
  runner/tests/conftest.py
  runner/tests/debug_fixture.py
  runner/tests/executor/test_execute_operation_with_server_vars.py
  runner/tests/executor/test_operation_finder.py
  runner/tests/executor/test_parameter_processor.py
  runner/tests/executor/test_server_processor.py
  runner/tests/extractor/test_openapi_extractor.py
  runner/tests/mocks/__init__.py
  runner/tests/mocks/http_client.py
  runner/tests/mocks/openapi_mocker.py
  runner/tests/mocks/real_http_client.py
  runner/tests/test_arazzo_runner.py
  runner/tests/test_blob_store.py
  runner/tests/test_env_mappings.py
  runner/tests/test_evaluator.py
  runner/tests/test_fixture_discovery.py
  runner/tests/test_framework_demo.py
  runner/tests/test_http_client.py
  runner/tests/test_utils.py
  runner/tests/test_workflow_execution_result.py
Labels: enhancement

#32 ci: enhance Arazzo Runner CI pipeline
  .github/workflows/arazzo-runner.yml
  .github/workflows/test.yml
Labels: enhancement, CICD

#33 ci(arazzo-runner): shorten the workflow name
  .github/workflows/arazzo-runner.yml
Labels: enhancement, CICD

#43 ci(dependabot): allow dependabot auto-updates for generator
  .github/dependabot.yml
Labels: enhancement, CICD

#45 ci: add Arazzo Generator initial CI pipeline
  .github/workflows/arazzo-generator.yml
Labels: enhancement, CICD

#44 test(generator): make all tests to run successfully
  .github/workflows/arazzo-generator.yml
  generator/.gitignore
  generator/arazzo_generator/llm/prompts/user_workflow_instructions_prompt.txt
  generator/tests/analyzers/llm_response_mock.txt
  generator/tests/api/test_app.py
  generator/tests/generator/test_reference_validator.py
  generator/tests/llm/test_llm_service_prompt_builders.py
Labels: enhancement, tests

#49 revert: add potential fix for reading local refs
  generator/arazzo_generator/parser/openapi_parser.py
Labels: enhancement, security

#50 docs(parser): align docs with the code
  generator/arazzo_generator/parser/openapi_parser.py
Labels: documentation, enhancement

#52 fix(generator): eliminate catastrophic backtracking vulnerability in parser
  generator/arazzo_generator/parser/openapi_parser.py
Labels: enhancement, security

#54 refactor(generator): simplify how parser handles URI manipulation
  generator/arazzo_generator/parser/openapi_parser.py
Labels: enhancement

#66 chore(release): cut the arazzo_generator v0.1.0 release
  generator/pyproject.toml
Labels: enhancement, CICD

#67 docs(SECURITY): add Arazzo Generator section
  SECURITY.md
Labels: documentation, enhancement

#69 ci(arazzo-runner-pypi): remove TestPypi publishing
  .github/workflows/arazzo-runner-pypi.yaml
Labels: enhancement, CICD

#68 ci(arazzo-generator-pypi): remove TestPypi publishing
  .github/workflows/arazzo-generator-pypi.yaml
Labels: enhancement, CICD

#79 fix(generator): allow generator CLI to run
  generator/arazzo_generator/__main__.py
Labels: bug, generator

#75 ci: consolidate enforcing of code consistency
  generator/pyproject.toml
  runner/pyproject.toml
Labels: enhancement, CICD, runner, generator

#83 chore(release): cut the arazzo_generator v0.1.1 release
  generator/pyproject.toml
Labels: CICD
